export const dummyMlbStandings = [
  {
    teamAbv: "ARI",
    teamCity: "Arizona",
    RS: "479",
    loss: "43",
    teamName: "Diamondbacks",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/109.svg",
    DIFF: "20",
    teamID: "1",
    division: "West",
    RA: "459",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/ari.png",
    wins: "53",
    conference: "National League",
  },
  {
    teamAbv: "ATL",
    teamCity: "Atlanta",
    RS: "530",
    loss: "33",
    teamName: "Braves",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/144.svg",
    DIFF: "143",
    teamID: "2",
    division: "East",
    RA: "387",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/atl.png",
    wins: "61",
    conference: "National League",
  },
  {
    teamAbv: "BAL",
    teamCity: "Baltimore",
    RS: "473",
    loss: "37",
    teamName: "Orioles",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/110.svg",
    DIFF: "47",
    teamID: "3",
    division: "East",
    RA: "426",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bal.png",
    wins: "58",
    conference: "American League",
  },
  {
    teamAbv: "BOS",
    teamCity: "Boston",
    RS: "486",
    loss: "46",
    teamName: "Red Sox",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/111.svg",
    DIFF: "35",
    teamID: "4",
    division: "East",
    RA: "451",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bos.png",
    wins: "51",
    conference: "American League",
  },
  {
    teamAbv: "CHC",
    teamCity: "Chicago",
    RS: "458",
    loss: "50",
    teamName: "Cubs",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/112.svg",
    DIFF: "38",
    teamID: "5",
    division: "Central",
    RA: "420",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chc.png",
    wins: "45",
    conference: "National League",
  },
  {
    teamAbv: "CHW",
    teamCity: "Chicago",
    RS: "407",
    loss: "57",
    teamName: "White Sox",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/145.svg",
    DIFF: "-73",
    teamID: "6",
    division: "Central",
    RA: "480",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chw.png",
    wins: "40",
    conference: "American League",
  },
  {
    teamAbv: "CIN",
    teamCity: "Cincinnati",
    RS: "472",
    loss: "46",
    teamName: "Reds",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/113.svg",
    DIFF: "-16",
    teamID: "7",
    division: "Central",
    RA: "488",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cin.png",
    wins: "51",
    conference: "National League",
  },
  {
    teamAbv: "CLE",
    teamCity: "Cleveland",
    RS: "400",
    loss: "49",
    teamName: "Guardians",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/114.svg",
    DIFF: "0",
    teamID: "8",
    division: "Central",
    RA: "400",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cle.png",
    wins: "47",
    conference: "American League",
  },
  {
    teamAbv: "COL",
    teamCity: "Colorado",
    RS: "416",
    loss: "59",
    teamName: "Rockies",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/115.svg",
    DIFF: "-146",
    teamID: "9",
    division: "West",
    RA: "562",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/col.png",
    wins: "37",
    conference: "National League",
  },
  {
    teamAbv: "DET",
    teamCity: "Detroit",
    RS: "373",
    loss: "52",
    teamName: "Tigers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/116.svg",
    DIFF: "-80",
    teamID: "10",
    division: "Central",
    RA: "453",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/det.png",
    wins: "43",
    conference: "American League",
  },
  {
    teamAbv: "HOU",
    teamCity: "Houston",
    RS: "452",
    loss: "43",
    teamName: "Astros",
    mlbLogo1:
      "https://www.mlbstatic.com/team-logos/team-primary-on-light/117.svg",
    DIFF: "53",
    teamID: "11",
    division: "West",
    RA: "399",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/hou.png",
    wins: "53",
    conference: "American League",
  },
  {
    teamAbv: "KC",
    teamCity: "Kansas City",
    RS: "363",
    loss: "69",
    teamName: "Royals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/118.svg",
    DIFF: "-159",
    teamID: "12",
    division: "Central",
    RA: "522",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/kc.png",
    wins: "28",
    conference: "American League",
  },
  {
    teamAbv: "LAA",
    teamCity: "Los Angeles",
    RS: "485",
    loss: "48",
    teamName: "Angels",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/108.svg",
    DIFF: "16",
    teamID: "13",
    division: "West",
    RA: "469",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/laa.png",
    wins: "49",
    conference: "American League",
  },
  {
    teamAbv: "LAD",
    teamCity: "Los Angeles",
    RS: "527",
    loss: "40",
    teamName: "Dodgers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/119.svg",
    DIFF: "91",
    teamID: "14",
    division: "West",
    RA: "436",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/lad.png",
    wins: "55",
    conference: "National League",
  },
  {
    teamAbv: "MIA",
    teamCity: "Miami",
    RS: "407",
    loss: "45",
    teamName: "Marlins",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/146.svg",
    DIFF: "-17",
    teamID: "15",
    division: "East",
    RA: "424",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mia.png",
    wins: "53",
    conference: "National League",
  },
  {
    teamAbv: "MIL",
    teamCity: "Milwaukee",
    RS: "400",
    loss: "43",
    teamName: "Brewers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/158.svg",
    DIFF: "-7",
    teamID: "16",
    division: "Central",
    RA: "407",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mil.png",
    wins: "53",
    conference: "National League",
  },
  {
    teamAbv: "MIN",
    teamCity: "Minnesota",
    RS: "422",
    loss: "47",
    teamName: "Twins",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/142.svg",
    DIFF: "41",
    teamID: "17",
    division: "Central",
    RA: "381",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/min.png",
    wins: "50",
    conference: "American League",
  },
  {
    teamAbv: "NYM",
    teamCity: "New York",
    RS: "424",
    loss: "50",
    teamName: "Mets",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/121.svg",
    DIFF: "-7",
    teamID: "18",
    division: "East",
    RA: "431",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nym.png",
    wins: "45",
    conference: "National League",
  },
  {
    teamAbv: "NYY",
    teamCity: "New York",
    RS: "422",
    loss: "47",
    teamName: "Yankees",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/147.svg",
    DIFF: "8",
    teamID: "19",
    division: "East",
    RA: "414",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nyy.png",
    wins: "50",
    conference: "American League",
  },
  {
    teamAbv: "OAK",
    teamCity: "Oakland",
    RS: "353",
    loss: "71",
    teamName: "Athletics",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/133.svg",
    DIFF: "-256",
    teamID: "20",
    division: "West",
    RA: "609",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/oak.png",
    wins: "27",
    conference: "American League",
  },
  {
    teamAbv: "PHI",
    teamCity: "Philadelphia",
    RS: "435",
    loss: "42",
    teamName: "Phillies",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/143.svg",
    DIFF: "13",
    teamID: "21",
    division: "East",
    RA: "422",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/phi.png",
    wins: "53",
    conference: "National League",
  },
  {
    teamAbv: "PIT",
    teamCity: "Pittsburgh",
    RS: "396",
    loss: "54",
    teamName: "Pirates",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/134.svg",
    DIFF: "-72",
    teamID: "22",
    division: "Central",
    RA: "468",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/pit.png",
    wins: "42",
    conference: "National League",
  },
  {
    teamAbv: "SD",
    teamCity: "San Diego",
    RS: "434",
    loss: "50",
    teamName: "Padres",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/135.svg",
    DIFF: "46",
    teamID: "23",
    division: "West",
    RA: "388",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sd.png",
    wins: "46",
    conference: "National League",
  },
  {
    teamAbv: "SF",
    teamCity: "San Francisco",
    RS: "450",
    loss: "42",
    teamName: "Giants",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/137.svg",
    DIFF: "41",
    teamID: "24",
    division: "West",
    RA: "409",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sf.png",
    wins: "54",
    conference: "National League",
  },
  {
    teamAbv: "SEA",
    teamCity: "Seattle",
    RS: "423",
    loss: "48",
    teamName: "Mariners",
    mlbLogo1:
      "https://www.mlbstatic.com/team-logos/team-primary-on-light/136.svg",
    DIFF: "22",
    teamID: "25",
    division: "West",
    RA: "401",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sea.png",
    wins: "47",
    conference: "American League",
  },
  {
    teamAbv: "STL",
    teamCity: "St. Louis",
    RS: "454",
    loss: "53",
    teamName: "Cardinals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/138.svg",
    DIFF: "-21",
    teamID: "26",
    division: "Central",
    RA: "475",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/stl.png",
    wins: "43",
    conference: "National League",
  },
  {
    teamAbv: "TB",
    teamCity: "Tampa Bay",
    RS: "526",
    loss: "39",
    teamName: "Rays",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/139.svg",
    DIFF: "145",
    teamID: "27",
    division: "East",
    RA: "381",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tb.png",
    wins: "60",
    conference: "American League",
  },
  {
    teamAbv: "TEX",
    teamCity: "Texas",
    RS: "564",
    loss: "39",
    teamName: "Rangers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/140.svg",
    DIFF: "166",
    teamID: "28",
    division: "West",
    RA: "398",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tex.png",
    wins: "58",
    conference: "American League",
  },
  {
    teamAbv: "TOR",
    teamCity: "Toronto",
    RS: "430",
    loss: "43",
    teamName: "Blue Jays",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/141.svg",
    DIFF: "34",
    teamID: "29",
    division: "East",
    RA: "396",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tor.png",
    wins: "53",
    conference: "American League",
  },
  {
    teamAbv: "WAS",
    teamCity: "Washington",
    RS: "403",
    loss: "58",
    teamName: "Nationals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/120.svg",
    DIFF: "-105",
    teamID: "30",
    division: "East",
    RA: "508",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/wsh.png",
    wins: "38",
    conference: "National League",
  },
];
