export const dummyMlbTeams = [
  {
    teamAbv: "ARI",
    teamCity: "Arizona",
    RS: "526",
    loss: "53",
    teamName: "Diamondbacks",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/109.svg",
    DIFF: "-4",
    teamID: "1",
    division: "West",
    RA: "530",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/ari.png",
    wins: "57",
    conference: "National League",
  },
  {
    teamAbv: "ATL",
    teamCity: "Atlanta",
    RS: "601",
    loss: "37",
    teamName: "Braves",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/144.svg",
    DIFF: "159",
    teamID: "2",
    division: "East",
    RA: "442",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/atl.png",
    wins: "69",
    conference: "National League",
  },
  {
    teamAbv: "BAL",
    teamCity: "Baltimore",
    RS: "535",
    loss: "42",
    teamName: "Orioles",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/110.svg",
    DIFF: "62",
    teamID: "3",
    division: "East",
    RA: "473",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bal.png",
    wins: "67",
    conference: "American League",
  },
  {
    teamAbv: "BOS",
    teamCity: "Boston",
    RS: "535",
    loss: "51",
    teamName: "Red Sox",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/111.svg",
    DIFF: "43",
    teamID: "4",
    division: "East",
    RA: "492",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/bos.png",
    wins: "57",
    conference: "American League",
  },
  {
    teamAbv: "CHC",
    teamCity: "Chicago",
    RS: "560",
    loss: "53",
    teamName: "Cubs",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/112.svg",
    DIFF: "79",
    teamID: "5",
    division: "Central",
    RA: "481",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chc.png",
    wins: "56",
    conference: "National League",
  },
  {
    teamAbv: "CHW",
    teamCity: "Chicago",
    RS: "450",
    loss: "67",
    teamName: "White Sox",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/145.svg",
    DIFF: "-97",
    teamID: "6",
    division: "Central",
    RA: "547",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/chw.png",
    wins: "43",
    conference: "American League",
  },
  {
    teamAbv: "CIN",
    teamCity: "Cincinnati",
    RS: "544",
    loss: "52",
    teamName: "Reds",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/113.svg",
    DIFF: "-19",
    teamID: "7",
    division: "Central",
    RA: "563",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cin.png",
    wins: "59",
    conference: "National League",
  },
  {
    teamAbv: "CLE",
    teamCity: "Cleveland",
    RS: "446",
    loss: "56",
    teamName: "Guardians",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/114.svg",
    DIFF: "-1",
    teamID: "8",
    division: "Central",
    RA: "447",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/cle.png",
    wins: "53",
    conference: "American League",
  },
  {
    teamAbv: "COL",
    teamCity: "Colorado",
    RS: "467",
    loss: "66",
    teamName: "Rockies",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/115.svg",
    DIFF: "-160",
    teamID: "9",
    division: "West",
    RA: "627",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/col.png",
    wins: "42",
    conference: "National League",
  },
  {
    teamAbv: "DET",
    teamCity: "Detroit",
    RS: "424",
    loss: "60",
    teamName: "Tigers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/116.svg",
    DIFF: "-95",
    teamID: "10",
    division: "Central",
    RA: "519",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/det.png",
    wins: "48",
    conference: "American League",
  },
  {
    teamAbv: "HOU",
    teamCity: "Houston",
    RS: "521",
    loss: "48",
    teamName: "Astros",
    mlbLogo1:
      "https://www.mlbstatic.com/team-logos/team-primary-on-light/117.svg",
    DIFF: "61",
    teamID: "11",
    division: "West",
    RA: "460",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/hou.png",
    wins: "62",
    conference: "American League",
  },
  {
    teamAbv: "KC",
    teamCity: "Kansas City",
    RS: "423",
    loss: "75",
    teamName: "Royals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/118.svg",
    DIFF: "-157",
    teamID: "12",
    division: "Central",
    RA: "580",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/kc.png",
    wins: "35",
    conference: "American League",
  },
  {
    teamAbv: "LAA",
    teamCity: "Los Angeles",
    RS: "542",
    loss: "54",
    teamName: "Angels",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/108.svg",
    DIFF: "15",
    teamID: "13",
    division: "West",
    RA: "527",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/laa.png",
    wins: "56",
    conference: "American League",
  },
  {
    teamAbv: "LAD",
    teamCity: "Los Angeles",
    RS: "603",
    loss: "45",
    teamName: "Dodgers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/119.svg",
    DIFF: "107",
    teamID: "14",
    division: "West",
    RA: "496",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/lad.png",
    wins: "62",
    conference: "National League",
  },
  {
    teamAbv: "MIA",
    teamCity: "Miami",
    RS: "450",
    loss: "52",
    teamName: "Marlins",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/146.svg",
    DIFF: "-26",
    teamID: "15",
    division: "East",
    RA: "476",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mia.png",
    wins: "58",
    conference: "National League",
  },
  {
    teamAbv: "MIL",
    teamCity: "Milwaukee",
    RS: "466",
    loss: "51",
    teamName: "Brewers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/158.svg",
    DIFF: "-2",
    teamID: "16",
    division: "Central",
    RA: "468",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mil.png",
    wins: "59",
    conference: "National League",
  },
  {
    teamAbv: "MIN",
    teamCity: "Minnesota",
    RS: "481",
    loss: "54",
    teamName: "Twins",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/142.svg",
    DIFF: "33",
    teamID: "17",
    division: "Central",
    RA: "448",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/min.png",
    wins: "56",
    conference: "American League",
  },
  {
    teamAbv: "NYM",
    teamCity: "New York",
    RS: "474",
    loss: "58",
    teamName: "Mets",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/121.svg",
    DIFF: "-22",
    teamID: "18",
    division: "East",
    RA: "496",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nym.png",
    wins: "50",
    conference: "National League",
  },
  {
    teamAbv: "NYY",
    teamCity: "New York",
    RS: "471",
    loss: "52",
    teamName: "Yankees",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/147.svg",
    DIFF: "8",
    teamID: "19",
    division: "East",
    RA: "463",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nyy.png",
    wins: "57",
    conference: "American League",
  },
  {
    teamAbv: "OAK",
    teamCity: "Oakland",
    RS: "393",
    loss: "80",
    teamName: "Athletics",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/133.svg",
    DIFF: "-274",
    teamID: "20",
    division: "West",
    RA: "667",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/oak.png",
    wins: "30",
    conference: "American League",
  },
  {
    teamAbv: "PHI",
    teamCity: "Philadelphia",
    RS: "489",
    loss: "50",
    teamName: "Phillies",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/143.svg",
    DIFF: "13",
    teamID: "21",
    division: "East",
    RA: "476",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/phi.png",
    wins: "59",
    conference: "National League",
  },
  {
    teamAbv: "PIT",
    teamCity: "Pittsburgh",
    RS: "443",
    loss: "60",
    teamName: "Pirates",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/134.svg",
    DIFF: "-84",
    teamID: "22",
    division: "Central",
    RA: "527",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/pit.png",
    wins: "48",
    conference: "National League",
  },
  {
    teamAbv: "SD",
    teamCity: "San Diego",
    RS: "503",
    loss: "55",
    teamName: "Padres",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/135.svg",
    DIFF: "75",
    teamID: "23",
    division: "West",
    RA: "428",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sd.png",
    wins: "54",
    conference: "National League",
  },
  {
    teamAbv: "SF",
    teamCity: "San Francisco",
    RS: "488",
    loss: "49",
    teamName: "Giants",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/137.svg",
    DIFF: "27",
    teamID: "24",
    division: "West",
    RA: "461",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sf.png",
    wins: "61",
    conference: "National League",
  },
  {
    teamAbv: "SEA",
    teamCity: "Seattle",
    RS: "496",
    loss: "52",
    teamName: "Mariners",
    mlbLogo1:
      "https://www.mlbstatic.com/team-logos/team-primary-on-light/136.svg",
    DIFF: "43",
    teamID: "25",
    division: "West",
    RA: "453",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sea.png",
    wins: "57",
    conference: "American League",
  },
  {
    teamAbv: "STL",
    teamCity: "St. Louis",
    RS: "515",
    loss: "62",
    teamName: "Cardinals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/138.svg",
    DIFF: "-26",
    teamID: "26",
    division: "Central",
    RA: "541",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/stl.png",
    wins: "48",
    conference: "National League",
  },
  {
    teamAbv: "TB",
    teamCity: "Tampa Bay",
    RS: "573",
    loss: "45",
    teamName: "Rays",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/139.svg",
    DIFF: "137",
    teamID: "27",
    division: "East",
    RA: "436",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tb.png",
    wins: "66",
    conference: "American League",
  },
  {
    teamAbv: "TEX",
    teamCity: "Texas",
    RS: "627",
    loss: "46",
    teamName: "Rangers",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/140.svg",
    DIFF: "159",
    teamID: "28",
    division: "West",
    RA: "468",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tex.png",
    wins: "63",
    conference: "American League",
  },
  {
    teamAbv: "TOR",
    teamCity: "Toronto",
    RS: "491",
    loss: "50",
    teamName: "Blue Jays",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/141.svg",
    DIFF: "39",
    teamID: "29",
    division: "East",
    RA: "452",
    conferenceAbv: "AL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tor.png",
    wins: "60",
    conference: "American League",
  },
  {
    teamAbv: "WAS",
    teamCity: "Washington",
    RS: "468",
    loss: "63",
    teamName: "Nationals",
    mlbLogo1: "https://www.mlbstatic.com/team-logos/team-cap-on-light/120.svg",
    DIFF: "-93",
    teamID: "30",
    division: "East",
    RA: "561",
    conferenceAbv: "NL",
    espnLogo1:
      "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/wsh.png",
    wins: "46",
    conference: "National League",
  },
];
