export const dummyMlbMatch = {
  "20230510_BOS@ATL": {
    away: "BOS",
    home: "ATL",
    teamIDAway: "4",
    teamIDHome: "2",
    gameTime: "7:22p",
    gameTime_epoch: "1683760920.0",
    lineScore: {
      away: {
        H: "7",
        R: "5",
        team: "BOS",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "2",
          "5": "0",
          "6": "0",
          "7": "1",
          "8": "0",
          "9": "2",
        },
        E: "0",
      },
      home: {
        H: "8",
        R: "2",
        team: "ATL",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "2",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_BOS@ATL",
    gameStatus: "Completed",
  },
  "20230510_NYM@CIN": {
    away: "NYM",
    home: "CIN",
    teamIDAway: "18",
    teamIDHome: "7",
    gameTime: "6:40p",
    gameTime_epoch: "1683758400.0",
    lineScore: {
      away: {
        H: "10",
        R: "2",
        team: "NYM",
        scoresByInning: {
          "1": "0",
          "2": "1",
          "3": "0",
          "4": "1",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "2",
        R: "1",
        team: "CIN",
        scoresByInning: {
          "1": "1",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_NYM@CIN",
    gameStatus: "Completed",
  },
  "20230510_TOR@PHI": {
    away: "TOR",
    home: "PHI",
    teamIDAway: "29",
    teamIDHome: "21",
    gameTime: "4:08p",
    gameTime_epoch: "1683749280.0",
    lineScore: {
      away: {
        H: "4",
        R: "1",
        team: "TOR",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "1",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
          "10": "0",
        },
        E: "1",
      },
      home: {
        H: "7",
        R: "2",
        team: "PHI",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "1",
          "10": "1",
        },
        E: "0",
      },
    },
    currentInning: "Final/10",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_TOR@PHI",
    gameStatus: "Completed",
  },
  "20230510_MIA@ARI": {
    away: "MIA",
    home: "ARI",
    teamIDAway: "15",
    teamIDHome: "1",
    gameTime: "12:40p",
    gameTime_epoch: "1683736800.0",
    lineScore: {
      away: {
        H: "7",
        R: "5",
        team: "MIA",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "3",
          "5": "1",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "1",
        },
        E: "0",
      },
      home: {
        H: "5",
        R: "4",
        team: "ARI",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "4",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_MIA@ARI",
    gameStatus: "Completed",
  },
  "20230510_LAD@MIL": {
    away: "LAD",
    home: "MIL",
    teamIDAway: "14",
    teamIDHome: "16",
    gameTime: "12:40p",
    gameTime_epoch: "1683736800.0",
    lineScore: {
      away: {
        H: "9",
        R: "8",
        team: "LAD",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "2",
          "5": "2",
          "6": "4",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "5",
        R: "1",
        team: "MIL",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "1",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_LAD@MIL",
    gameStatus: "Completed",
  },
  "20230510_TB@BAL": {
    away: "TB",
    home: "BAL",
    teamIDAway: "27",
    teamIDHome: "3",
    gameTime: "6:37p",
    gameTime_epoch: "1683758220.0",
    lineScore: {
      away: {
        H: "6",
        R: "1",
        team: "TB",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "1",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "6",
        R: "2",
        team: "BAL",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "2",
          "7": "0",
          "8": "0",
          "9": "x",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_TB@BAL",
    gameStatus: "Completed",
  },
  "20230510_TEX@SEA": {
    away: "TEX",
    home: "SEA",
    teamIDAway: "28",
    teamIDHome: "25",
    gameTime: "12:40p",
    gameTime_epoch: "1683736800.0",
    lineScore: {
      away: {
        H: "13",
        R: "4",
        team: "TEX",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "3",
          "4": "0",
          "5": "0",
          "6": "1",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
      home: {
        H: "7",
        R: "3",
        team: "SEA",
        scoresByInning: {
          "1": "1",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "1",
          "6": "0",
          "7": "0",
          "8": "1",
          "9": "0",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_TEX@SEA",
    gameStatus: "Completed",
  },
  "20230510_CHW@KC": {
    away: "CHW",
    home: "KC",
    teamIDAway: "6",
    teamIDHome: "12",
    gameTime: "6:40p",
    gameTime_epoch: "1683758400.0",
    lineScore: {
      away: {
        H: "6",
        R: "1",
        team: "CHW",
        scoresByInning: {
          "1": "0",
          "2": "1",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
      home: {
        H: "14",
        R: "9",
        team: "KC",
        scoresByInning: {
          "1": "4",
          "2": "0",
          "3": "0",
          "4": "1",
          "5": "2",
          "6": "1",
          "7": "1",
          "8": "0",
          "9": "x",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_CHW@KC",
    gameStatus: "Completed",
  },
  "20230510_OAK@NYY": {
    away: "OAK",
    home: "NYY",
    teamIDAway: "20",
    teamIDHome: "19",
    gameTime: "12:39p",
    gameTime_epoch: "1683736740.0",
    lineScore: {
      away: {
        H: "8",
        R: "3",
        team: "OAK",
        scoresByInning: {
          "1": "0",
          "2": "2",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "1",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "10",
        R: "11",
        team: "NYY",
        scoresByInning: {
          "1": "4",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "7",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "x",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_OAK@NYY",
    gameStatus: "Completed",
  },
  "20230510_WAS@SF": {
    away: "WAS",
    home: "SF",
    teamIDAway: "30",
    teamIDHome: "24",
    gameTime: "12:44p",
    gameTime_epoch: "1683737040.0",
    lineScore: {
      away: {
        H: "12",
        R: "11",
        team: "WAS",
        scoresByInning: {
          "1": "0",
          "2": "4",
          "3": "4",
          "4": "1",
          "5": "0",
          "6": "1",
          "7": "0",
          "8": "0",
          "9": "1",
        },
        E: "0",
      },
      home: {
        H: "8",
        R: "6",
        team: "SF",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "1",
          "4": "0",
          "5": "0",
          "6": "1",
          "7": "0",
          "8": "2",
          "9": "2",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_WAS@SF",
    gameStatus: "Completed",
  },
  "20230510_COL@PIT": {
    away: "COL",
    home: "PIT",
    teamIDAway: "9",
    teamIDHome: "22",
    gameTime: "12:35p",
    gameTime_epoch: "1683736500.0",
    lineScore: {
      away: {
        H: "8",
        R: "4",
        team: "COL",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "3",
          "5": "0",
          "6": "0",
          "7": "1",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "6",
        R: "3",
        team: "PIT",
        scoresByInning: {
          "1": "0",
          "2": "1",
          "3": "2",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_COL@PIT",
    gameStatus: "Completed",
  },
  "20230510_STL@CHC": {
    away: "STL",
    home: "CHC",
    teamIDAway: "26",
    teamIDHome: "5",
    gameTime: "6:39p",
    gameTime_epoch: "1683758340.0",
    lineScore: {
      away: {
        H: "10",
        R: "4",
        team: "STL",
        scoresByInning: {
          "1": "1",
          "2": "0",
          "3": "1",
          "4": "0",
          "5": "0",
          "6": "1",
          "7": "0",
          "8": "0",
          "9": "1",
        },
        E: "0",
      },
      home: {
        H: "14",
        R: "10",
        team: "CHC",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "3",
          "4": "2",
          "5": "1",
          "6": "3",
          "7": "1",
          "8": "0",
          "9": "x",
        },
        E: "0",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_STL@CHC",
    gameStatus: "Completed",
  },
  "20230510_HOU@LAA": {
    away: "HOU",
    home: "LAA",
    teamIDAway: "11",
    teamIDHome: "13",
    gameTime: "1:08p",
    gameTime_epoch: "1683738480.0",
    lineScore: {
      away: {
        H: "8",
        R: "5",
        team: "HOU",
        scoresByInning: {
          "1": "1",
          "2": "0",
          "3": "0",
          "4": "4",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "8",
        R: "4",
        team: "LAA",
        scoresByInning: {
          "1": "0",
          "2": "2",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "2",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_HOU@LAA",
    gameStatus: "Completed",
  },
  "20230510_SD@MIN": {
    away: "SD",
    home: "MIN",
    teamIDAway: "23",
    teamIDHome: "17",
    gameTime: "6:41p",
    gameTime_epoch: "1683758460.0",
    lineScore: {
      away: {
        H: "4",
        R: "3",
        team: "SD",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "1",
          "8": "1",
          "9": "0",
          "10": "1",
          "11": "0",
        },
        E: "0",
      },
      home: {
        H: "9",
        R: "4",
        team: "MIN",
        scoresByInning: {
          "1": "1",
          "2": "0",
          "3": "1",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
          "10": "1",
          "11": "1",
        },
        E: "1",
      },
    },
    currentInning: "Final/11",
    currentCount: "",
    currentOuts: "",
    awayResult: "L",
    homeResult: "W",
    gameID: "20230510_SD@MIN",
    gameStatus: "Completed",
  },
  "20230510_DET@CLE": {
    away: "DET",
    home: "CLE",
    teamIDAway: "10",
    teamIDHome: "8",
    gameTime: "1:10p",
    gameTime_epoch: "1683738600.0",
    lineScore: {
      away: {
        H: "8",
        R: "5",
        team: "DET",
        scoresByInning: {
          "1": "2",
          "2": "0",
          "3": "3",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "0",
      },
      home: {
        H: "4",
        R: "0",
        team: "CLE",
        scoresByInning: {
          "1": "0",
          "2": "0",
          "3": "0",
          "4": "0",
          "5": "0",
          "6": "0",
          "7": "0",
          "8": "0",
          "9": "0",
        },
        E: "1",
      },
    },
    currentInning: "Final",
    currentCount: "",
    currentOuts: "",
    awayResult: "W",
    homeResult: "L",
    gameID: "20230510_DET@CLE",
    gameStatus: "Completed",
  },
};
